### ISSUE TITLE
Trying to get property 'categories' of non-object

### ISSUE THREAD

**Issue by micknolans** [NNTmux/newznab-tmux#942]
dev fresh install as well as latest update same issue

getting `Trying to get property 'categories' of non-object`

every time click on browse all   error: Undefined variable: browse
every time click on movie,console,music, etc.  error :Trying to get property 'categories' of non-object

**Comment by DariusIII** [comment]
Edit your .env and set APP_ENV to local and APP_DEBUG to true, and then report the complete error.

**Comment by boppen** [comment]
The problem seems to be the change to use the root_categories table and no migration script to put data into it.

Inserting the data myself using the query below solved the problem for me.

`INSERT INTO root_categories(id, title, status, disablepreview, created_at, updated_at) (SELECT id, title, status, disablepreview, NOW(), NOW() FROM categories WHERE root_categories_id IS NULL);`

**Comment by micknolans** [comment]
thankyou, Inserting the data myself all fixed

**Comment by DariusIII** [comment]
Since it is in dev, i have not added instructions. What you need to do, for next time this happens is following:

`php artisan fixtures:down --table=root_categories --table=categories`

`php artisan fixtures:up --table=root_categories --table=categories`

**Comment by micknolans** [comment]
not sure if part of same problem.

releases are being posted but every run of update releases in tmux window you can see 1 crossposted post deleted , seems to delete one by one every run.

cross posted setting in admin set to 2

**Comment by micknolans** [comment]
seems a related problem, only noticed one updated
in tmux panel (update releases)
i have noticed its deleting 1 releases every time it runs (1 cross posted release deleted)

**Comment by DariusIII** [comment]
That issue is unrelated to this one.
